language: php

php:
  - 7.2

services:
  - mysql

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS zanichelli_idp;'
  - cp .env.example .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate:fresh --seed --no-interaction
  - php artisan passport:install
  - php artisan jwt:secret --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash) -t ab59f408-dd5d-405d-9695-14dc5aa3b1da
